dist: xenial
python: 3.6
language: python
os: linux
env: PYTHON=/usr/bin/python3.6
before_install:
- sudo apt-get install -y libgtest-dev
- pip install ruamel.yaml schema setuptools cpplint datetime nose
- pip install flake8 coverage codacy-coverage
- ls /usr/src/
install:
- python setup.py develop
script:
- python setup.py nosetests -s
after_success:
- python-codacy-coverage -r coverage.xml
notifications:
  email: false
deploy:
  provider: pypi
  user: niosus
  password:
    secure: hoR4s3ONvCPW8+GObjUfLI6I7Afuimre0ZF2ncbF9XXkPVIgTzXMkU1lCcNcxVsfQQK2iki1O+ke3OM2g5kIwrBCfar2SxNkx2uqYt/a7Ilc78g7raejIORiuwYSlHUHsxhswy+KmYmSu92Wu+RPDQ4aSmL+2P7KkIUly1QMrx2Itp6NQgJ8oqPkLm10qUGzBM3cAnDwthndoxrkB/8NOeXGapATN8x/dCswkpvLb6jc4aZug5hsWDU4SYH3o7FR0H/QSwJ+qATPrBja+t+lhmkLxwiKS9tFlZB/v0vmGEIohRFHbg16UJliwI17Ph/DvRm4pHKThHXaz7THFdBkY3ZUfql0ASwztvlnS0EaYaol2hKQxGj7pGP5SrU1Fs+iNl4Bfz7x9e20w5R2N4RsQrTJbSj+92L27jNH+Ez0lcKC+ClPvYArYr9NgjW/TPVcqeZjknhDeWTuALb7jYNPH21vDq0tumOdeDoSpxgG/+DATjS4gMkf8R8vmJBzCw4mlIwicGJGziuxX/ZOJSmkzuNY7Vuqe+4f/yNZb/QrYX2wv74H8357asiYl638Ug3fsY755aFjePOyGQV+kc85GhibgTOjHg2qVXJSjEjUCSRxqUzWaer5RwB+iKMEyw3Anim5X2OACuKvdU1PHe7qXaW0TSnCbX6x96FtOCnd07I=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: PRBonn/ipb_homework_checker
