---
folder: <class 'str'>
homeworks:
  - folder: <class 'str'>
    name: <class 'str'>
    tasks:
      - folder: <class 'str'>
        language: "Possible values: ['cpp', 'bash']"
        name: <class 'str'>
        ~[optional]~ binary_name: <class 'str'>
        ~[optional]~ build_type: "Possible values: ['cmake', 'simple']"
        ~[optional]~ input_args: <class 'str'>
        ~[optional]~ output_type: "Possible values: ['string', 'number']"
        ~[optional]~ tests:
          - expected_output: Or(<class 'str'>, <class 'float'>, <class 'int'>)
            name: <class 'str'>
            ~[optional]~ input_args: <class 'str'>
