---
folder: str
homeworks:
  - folder: str
    name: str
    tasks:
      - folder: str
        language: Any of ['cpp', 'bash']
        name: str
        ~[optional]~ binary_name: str
        ~[optional]~ build_type: Any of ['cmake', 'simple']
        ~[optional]~ output_type: Any of ['string', 'number']
        ~[optional]~ tests:
          - name: str
            ~[optional]~ expected_output: Any of ['str', 'float', 'int']
            ~[optional]~ input_args: str
