folder: <class 'str'>
exercises:
- build_type [OPTIONAL]: "Possible values: ['cmake', 'simple']"
  output_type: "Possible values: ['string', 'number']"
  language: "Possible values: ['cpp']"
  tests:
  - name: <class 'str'>
    input_args [OPTIONAL]: <class 'str'>
    expected_output: Or(<class 'str'>, <class 'float'>, <class 'int'>)
  binary_name [OPTIONAL]: <class 'str'>
  folder: <class 'str'>
  name: <class 'str'>
  input_args [OPTIONAL]: <class 'str'>
