folder: <class 'str'>
homeworks:
- folder: <class 'str'>
  exercises:
  - folder: <class 'str'>
    language: "Possible values: ['cpp']"
    name: <class 'str'>
    input_args [OPTIONAL]: <class 'str'>
    build_type [OPTIONAL]: "Possible values: ['cmake', 'simple']"
    tests:
    - input_args [OPTIONAL]: <class 'str'>
      name: <class 'str'>
      expected_output: Or(<class 'str'>, <class 'float'>, <class 'int'>)
    binary_name [OPTIONAL]: <class 'str'>
    output_type: "Possible values: ['string', 'number']"
  name: <class 'str'>
