folder: <class 'str'>
exercises:
- folder: <class 'str'>
  tests:
  - name: <class 'str'>
    expected_output: Or(<class 'str'>, <class 'float'>, <class 'int'>)
    input_args [OPTIONAL]: <class 'str'>
  language: "Possible values: ['cpp']"
  binary_name [OPTIONAL]: <class 'str'>
  build_type [OPTIONAL]: "Possible values: ['cmake', 'simple']"
  name: <class 'str'>
  output_type: "Possible values: ['string', 'number']"
  input_args [OPTIONAL]: <class 'str'>
